name: iOS build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ env.WEST_IOS_REPOSITORY }}
          ref: ${{ github.head_ref }}
          token: ${{ secrets.WEST_CHECKOUT_TOKEN }}
      - name: Hello world
        run: |
          echo "Hello world"
